name: Build OpenFros Firmware

on: [push, pull_request]

jobs:
  build-openfros:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev libssl-dev git subversion

    - name: Download and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run build script
      run: |
        ./build.sh

    - name: Check if bin/targets directory exists
      id: check_dir
      run: |
        if [ -d "bin/targets" ]; then
          echo "Directory bin/targets exists."
        else
          echo "Directory bin/targets does not exist."
          exit 1
        fi

    - name: List files in bin/targets
      if: steps.check_dir.outcome == 'success'
      run: |
        ls -la bin/targets

    - name: Find firmware files
      if: steps.check_dir.outcome == 'success'
      run: |
        firmware_files=$(find bin/targets/*/* -type f)
        if [ -z "$firmware_files" ]; then
          echo "No firmware files found."
          exit 1
        else
          echo "Firmware files found: $firmware_files"
          echo "FIRMWARE_FILES=$firmware_files" >> $GITHUB_ENV
        fi

    - name: Upload artifacts
      if: env.FIRMWARE_FILES
      uses: actions/upload-artifact@v3
      with:
        name: OpenFros-Firmware
        path: ${{ env.FIRMWARE_FILES }}
        
    - name: Clean up
      run: |
        # Optional: Add any cleanup commands here
