name: Build OpenFros Firmware

on: [push, pull_request]

jobs:
  build-openfros:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 升级到最新版本

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev libssl-dev git subversion

    - name: Download and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run build script
      run: |
        ./build.sh

    - name: Check for firmware files
      id: check_files
      run: |
        echo "Firmware files found: $(find bin/targets/*/* -type f)"
        echo "::set-output name=firmware_files::$(find bin/targets/*/* -type f)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success() && steps.check_files.outputs.firmware_files
      with:
        name: OpenFros-Firmware
        path: ${{ steps.check_files.outputs.firmware_files }}
        
    - name: Clean up
      run: |
        # Optional: Add any cleanup commands here
