name: Build Fros Firmware

on: [push, pull_request]

jobs:
  build-fros:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: destan19/openfros
        path: openfros

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # 选择一个合适的Python版本

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gzip subversion git-core diffutils patch unzip quilt libssl-dev libexpat-dev

    - name: Download and install feeds
      run: |
        cd openfros
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile firmware using menuconfig
      run: |
        cd openfros
        make menuconfig # 可以选择配置
        # 等待用户输入配置并保存退出
        make -j$(nproc) V=s

    - name: Compile firmware using build.sh (if exists)
      run: |
        cd openfros
        if [ -f build.sh ]; then
          ./build.sh
        else
          echo "build.sh script not found, skipping..."
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: fros-firmware
        path: openfros/bin/
