name: Build OpenWrt for MT7620 (PSG1218)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the build environment
    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3

    # Step 3: Run the build script
    - name: Run build.sh script
      run: |
        chmod +x build.sh
        ./build.sh

    # Step 4: Upload the compiled firmware as an artifact
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./release/
