name: Build and Install Feeds

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Clone the repository
      run: git clone https://github.com/destan19/openfros.git

    - name: Update and install feeds
      run: |
        cd openfros
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build project
      run: ./build.sh
