name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install additional dependencies
      run: |
        sudo apt-get install -y dfu-util libncurses5-dev gawk gettext unzip file libssl-dev wget python3

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./release/
